export enum ROUTER_PATH {
  HOME = '/',
  PROFILE = '/profile',
  USERS = '/users',
  CLIENTS = '/clients',
  CLIENT = '/clients:id',
  GROUP = '/group',
  AGENT = '/agent',
  CONTRACT = '/contract',
  DEALS = '/deals',
  SETTINGS = '/setting',
  LOGIN = '/login',
  REGISTER = '/register',
  NOTFOUNDPAGE = '*',
}
