create table if not exists client(
    id integer not null generated by default as identity PRIMARY KEY,
    last_name varchar(255),
    first_name varchar(255),
    middle_name varchar(255),
    birthday date,
    sex integer,
    email varchar (255),
    mobile_phone varchar (255)
);

create table if not exists abonement(
    id integer not null generated by default as identity PRIMARY KEY,
    date_created timestamp,
    date_experied timestamp,
    client_id integer,
    constraint fk_client foreign key (client_id) references client(id)
);

create table if not exists contract(
    id integer not null generated by default as identity PRIMARY KEY,
    date_created timestamp,
    client_id integer,
    abonement_id integer,
    constraint fk_client foreign key (client_id) references client(id),
    constraint fk_abonement foreign key (abonement_id) references abonement(id)
);

create table if not exists appuser
(
    id integer not null generated by default as identity PRIMARY KEY,
    last_name varchar(255),
    first_name varchar(255),
    middle_name varchar(255),
    username varchar(100) not null,
    password varchar(100) not null,
    avatar varchar(100),
    account_nonexpired boolean,
    account_nonlocked boolean,
    credentials_nonexpired boolean,
    is_enabled boolean
);

create table if not exists role(
    id integer not null generated by default as identity PRIMARY KEY,
    role_name varchar(255)
);

create table if not exists appuser_role(
    appuser_id integer references appuser,
    role_id integer references role
);
